abstract class Payment {
   abstract void makePayment(int amount);
}

class CardPayment extends Payment {
    @Override
    void makePayment(int amount) {
        System.out.println("Amount paid using card... " + amount);
    }

    void generateBill() {
        System.out.println("Bill generated by card paymemnt");
    }
}

class UpiPayment extends Payment {
    @Override
    void makePayment(int amount) {
        System.out.println("Amount paid using upi id... " + amount);
    }

    void generateBill() {
        System.out.println("Bill generated by upi paymemnt");
    }
}

class PaymentService {
    void processPayment(Payment payment, int amount) {
        payment.makePayment(amount);
        
        if(payment instanceof CardPayment) {
            ((CardPayment) payment).generateBill();
        }
        else {
            ((UpiPayment) payment).generateBill();
        }
    }

    public static void main(String[] args) {
        PaymentService service = new PaymentService();
        // if we select card payment
        service.processPayment(new CardPayment(), 5000);

        // if we select upi payment
        service.processPayment(new UpiPayment(), 3000);
    }
}